spring:
  liquibase:
    enabled: false
  application:
    name: navigation
  server:
    port: 8081
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/navigation
    username: postgres
    password: root

